language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION == '7.0' || $TRAVIS_PHP_VERSION == 'nightly' ]]; then echo 'opcache.load_comments = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - if [[ $TRAVIS_PHP_VERSION == '7.0' || $TRAVIS_PHP_VERSION == 'nightly' ]]; then echo 'zend_optimizerplus.load_comments = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
